'use client';
import {ArrowRightLeft,BadgeDollarSign,BarChart3,Bell,Boxes,Building2,ChevronDown,ChevronRight,CircleUserRound,CreditCard,LayoutGrid,MapPin,Menu,Minus,PackageCheck,Plus,ReceiptText,Search,ShoppingBag,ShoppingCart,Store,Tag,Trash2,Truck,Users,WalletCards,X} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';

type Product={id:number;name:string;category:string;price:number;stock:number;color:string;icon:string};
type CartLine=Product&{quantity:number};
const products:Product[]=[
{id:1,name:'Cappuccino',category:'Beverages',price:42,stock:24,color:'#e8d7c0',icon:'☕'},{id:2,name:'Iced Matcha',category:'Beverages',price:48,stock:16,color:'#dce8c7',icon:'🍵'},{id:3,name:'Chicken Wrap',category:'Fresh food',price:72,stock:9,color:'#f0dfbd',icon:'🌯'},{id:4,name:'Avo Toast',category:'Fresh food',price:68,stock:12,color:'#d6e6c4',icon:'🥑'},{id:5,name:'Berry Bowl',category:'Fresh food',price:64,stock:7,color:'#edd1d9',icon:'🥣'},{id:6,name:'Butter Croissant',category:'Bakery',price:36,stock:18,color:'#f1dfb9',icon:'🥐'},{id:7,name:'Banana Bread',category:'Bakery',price:38,stock:6,color:'#e9d2ac',icon:'🍞'},{id:8,name:'Sparkling Water',category:'Cold drinks',price:24,stock:32,color:'#d3e6e8',icon:'💧'},{id:9,name:'Green Juice',category:'Cold drinks',price:52,stock:11,color:'#d6e7ca',icon:'🥤'},{id:10,name:'Granola Pack',category:'Retail',price:89,stock:15,color:'#e8ddca',icon:'🥜'},{id:11,name:'House Blend 250g',category:'Retail',price:145,stock:8,color:'#ded0c3',icon:'🫘'},{id:12,name:'Chocolate Cookie',category:'Bakery',price:28,stock:21,color:'#ead5c8',icon:'🍪'}];
const categories=['All items','Beverages','Fresh food','Bakery','Cold drinks','Retail'];
const navItems=[{label:'Sell',icon:ShoppingBag},{label:'Sites',icon:Building2},{label:'Inventory',icon:Boxes},{label:'Customers',icon:Users},{label:'Purchase orders',icon:Truck},{label:'Reports',icon:BarChart3}];
const clients=[{name:'Ubuntu Coffee Group',initials:'UC',sites:['Rosebank Café','Sandton Kiosk','Melrose Store']},{name:'Harbour Retail Co.',initials:'HR',sites:['V&A Waterfront','Sea Point Market']},{name:'Karoo Kitchen',initials:'KK',sites:['Stellenbosch','Paarl']}] as const;
const money=(value:number)=>`R ${value.toFixed(2)}`;

export default function Home(){
 const [activeNav,setActiveNav]=useState('Sell'),[category,setCategory]=useState('All items'),[query,setQuery]=useState(''),[menuOpen,setMenuOpen]=useState(false),[paid,setPaid]=useState(false),[clientIndex,setClientIndex]=useState(0),[siteIndex,setSiteIndex]=useState(0),[clientMenu,setClientMenu]=useState(false);
 const client=clients[clientIndex],activeSite=client.sites[Math.min(siteIndex,client.sites.length-1)];
 const [cart,setCart]=useState<CartLine[]>([{...products[0],quantity:2},{...products[3],quantity:1},{...products[5],quantity:1}]);
 const filtered=useMemo(()=>products.filter(p=>(category==='All items'||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
 const subtotal=cart.reduce((s,l)=>s+l.price*l.quantity,0),vat=subtotal*.15;
 const addProduct=(p:Product)=>{setPaid(false);setCart(c=>{const m=c.find(l=>l.id===p.id);return m?c.map(l=>l.id===p.id?{...l,quantity:l.quantity+1}:l):[...c,{...p,quantity:1}]})};
 const changeQuantity=(id:number,n:number)=>setCart(c=>c.map(l=>l.id===id?{...l,quantity:l.quantity+n}:l).filter(l=>l.quantity>0));
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'add_product_to_cart',title:'Add product to sale',description:'Add a product to the current POSPerity sale by product ID.',inputSchema:{type:'object',properties:{productId:{type:'number'}},required:['productId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const productId=(input as {productId?:unknown})?.productId;if(typeof productId!=='number')throw new Error('productId must be a number');const product=products.find(p=>p.id===productId);if(!product)throw new Error('Product not found');addProduct(product);return {productId,name:product.name,status:'added'};}},{signal:lifecycle.signal})).catch(()=>undefined);return()=>lifecycle.abort()},[]);
 return <main className="app-shell">
  <aside className={`sidebar ${menuOpen?'sidebar-open':''}`}><button className="sidebar-close" onClick={()=>setMenuOpen(false)} aria-label="Close menu"><X size={20}/></button><div className="brand"><span className="brand-mark"><BadgeDollarSign size={24}/></span><span>POS<span>Perity</span></span></div><div className="client-switcher"><button onClick={()=>setClientMenu(v=>!v)}><span className="client-logo">{client.initials}</span><span><small>CLIENT PORTAL</small><strong>{client.name}</strong></span><ChevronDown size={16}/></button>{clientMenu&&<div className="client-menu">{clients.map((item,index)=><button key={item.name} onClick={()=>{setClientIndex(index);setSiteIndex(0);setClientMenu(false)}} className={index===clientIndex?'selected-client':''}><span>{item.initials}</span><div><strong>{item.name}</strong><small>{item.sites.length} sites</small></div></button>)}</div>}</div><nav aria-label="Main navigation">{navItems.map(({label,icon:Icon})=><button key={label} className={activeNav===label?'nav-active':''} onClick={()=>{setActiveNav(label);setMenuOpen(false)}}><Icon size={20}/><span>{label}</span>{label==='Purchase orders'&&<span className="nav-badge">3</span>}</button>)}</nav><div className="sidebar-bottom"><div className="store-card"><span><Store size={19}/></span><div><strong>{activeSite}</strong><small>{client.sites.length} sites in this client</small></div><ChevronRight size={18}/></div><button className="profile"><span className="avatar">TM</span><span><strong>Thando M.</strong><small>Client administrator</small></span><ChevronDown size={17}/></button></div></aside>
  <section className="workspace"><header className="topbar"><div className="title-wrap"><button className="menu-button" onClick={()=>setMenuOpen(true)} aria-label="Open menu"><Menu/></button><div><p>{client.name} · Monday, 14 September</p><h1>{activeNav==='Sell'?'New sale':activeNav}</h1></div></div><div className="top-actions"><label className="site-select"><MapPin size={15}/><select value={siteIndex} onChange={e=>setSiteIndex(Number(e.target.value))}>{client.sites.map((site,index)=><option key={site} value={index}>{site}</option>)}</select><ChevronDown size={14}/></label><button aria-label="Notifications"><Bell size={20}/><span className="notification-dot"/></button><span className="register-status"><i/> Register open</span><button className="more-button">More <ChevronDown size={16}/></button></div></header>
  {activeNav==='Sell'?<div className="pos-layout"><section className="catalog"><div className="context-banner"><span><Building2 size={18}/></span><div><strong>{client.name}</strong><small>Selling from {activeSite} · Inventory controlled at client level</small></div><button onClick={()=>setActiveNav('Sites')}>Switch site <ChevronRight size={14}/></button></div><div className="search-row"><label className="search-box"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search client catalogue or scan barcode" aria-label="Search products"/><kbd>⌘ K</kbd></label><button className="scan-button"><LayoutGrid size={20}/><span>Quick keys</span></button></div><div className="category-tabs" role="tablist">{categories.map(item=><button key={item} role="tab" aria-selected={category===item} onClick={()=>setCategory(item)}>{item}</button>)}</div><div className="catalog-heading"><div><h2>{category}</h2><p>{filtered.length} products from {client.name}</p></div><button><Tag size={17}/> Price lookup</button></div><div className="product-grid">{filtered.map(p=><button className="product-card" key={p.id} onClick={()=>addProduct(p)}><span className="product-visual" style={{backgroundColor:p.color}}><span>{p.icon}</span><i className={p.stock<10?'stock-low':''}>{p.stock} at site</i></span><span className="product-meta"><strong>{p.name}</strong><small>{p.category}</small><b>{money(p.price)}</b></span><span className="add-button"><Plus size={18}/></span></button>)}</div></section>
  <aside className="cart-panel"><div className="cart-header"><div><h2>Current order</h2><span>{cart.reduce((s,l)=>s+l.quantity,0)} items</span></div><button onClick={()=>setCart([])} aria-label="Clear order"><Trash2 size={18}/></button></div><button className="customer-button"><span><CircleUserRound size={20}/></span><div><strong>Add customer</strong><small>Shared across {client.name}</small></div><Plus size={18}/></button><div className="cart-lines">{cart.length===0?<div className="empty-cart"><ShoppingCart size={34}/><strong>Your cart is empty</strong><span>Select a product to begin</span></div>:cart.map(l=><div className="cart-line" key={l.id}><span className="line-icon" style={{backgroundColor:l.color}}>{l.icon}</span><div className="line-details"><strong>{l.name}</strong><small>{money(l.price)} each</small><div className="quantity"><button onClick={()=>changeQuantity(l.id,-1)}><Minus size={14}/></button><b>{l.quantity}</b><button onClick={()=>changeQuantity(l.id,1)}><Plus size={14}/></button></div></div><b className="line-total">{money(l.price*l.quantity)}</b></div>)}</div><div className="totals"><p><span>Subtotal</span><b>{money(subtotal)}</b></p><p><span>VAT (15%) included</span><span>{money(vat)}</span></p><p className="grand-total"><span>Total</span><strong>{money(subtotal)}</strong></p></div>{paid&&<div className="paid-message"><PackageCheck size={22}/><div><strong>Payment approved</strong><span>Receipt #1048 is ready</span></div></div>}<button className="pay-button" disabled={!cart.length} onClick={()=>setPaid(true)}><span><CreditCard size={21}/> Pay</span><strong>{money(subtotal)}</strong></button><div className="payment-shortcuts"><button><WalletCards size={17}/> Hold</button><button><ReceiptText size={17}/> Discount</button><button><BadgeDollarSign size={17}/> Cash</button></div></aside></div>:<ModulePreview module={activeNav} client={client.name} sites={[...client.sites]} activeSite={activeSite} onSelectSite={index=>{setSiteIndex(index);setActiveNav('Sell')}} onBack={()=>setActiveNav('Sell')}/>}</section>
 </main>;
}

function ModulePreview({module,client,sites,activeSite,onSelectSite,onBack}:{module:string;client:string;sites:string[];activeSite:string;onSelectSite:(index:number)=>void;onBack:()=>void}){
 if(module==='Sites')return <div className="module-page"><div className="module-intro"><div><p>{client}</p><h2>Sites</h2><span>Manage every trading location from one client portal</span></div><button><Plus size={18}/> Add site</button></div><div className="site-grid">{sites.map((site,index)=><article key={site} className={site===activeSite?'active-site-card':''}><div><span><Store/></span><i>{site===activeSite?'Current site':'Online'}</i></div><h3>{site}</h3><p>{index===0?'Johannesburg, Gauteng':index===1?'Sandton, Gauteng':'Melrose, Gauteng'}</p><dl><div><dt>Sales today</dt><dd>{money(8940-index*1880)}</dd></div><div><dt>Stock alerts</dt><dd>{index+2}</dd></div></dl><button onClick={()=>onSelectSite(index)}>Open register <ChevronRight size={15}/></button></article>)}</div></div>;
 const details:Record<string,{subtitle:string;stats:[string,string][];rows:[string,string,string][]}>={Inventory:{subtitle:`Client-level stock control across ${sites.length} sites`,stats:[['1,248','Client units on hand'],['7','Low stock items'],['R 86.4k','Total inventory value']],rows:[['House Blend 250g','Rosebank 8 · Sandton 12 · Melrose 6','Transfer stock'],['Oat Milk 1L','Rosebank 6 · Sandton 18 · Melrose 10','Rebalance'],['Paper Cups 12oz','184 units across all sites','Healthy']]},Customers:{subtitle:`Profiles shared across every ${client} site`,stats:[['2,486','Total customers'],['184','Active this month'],['R 312','Average spend']],rows:[['Naledi Khumalo','12 visits','Gold member'],['James Williams','8 visits','Regular'],['Amara Jacobs','4 visits','New']]},'Purchase orders':{subtitle:'Purchase centrally and allocate stock to sites',stats:[['3','Open orders'],['1','Awaiting delivery'],['R 14.8k','On order']],rows:[['PO-0248 · Cape Coffee Co.','All sites','In transit'],['PO-0247 · Fresh Foods SA',activeSite,'Ready'],['PO-0246 · EcoPack','Central stock','Needs review']]},Reports:{subtitle:`Consolidated performance for ${client}`,stats:[['R 18,420','Client sales today'],['146','Transactions'],['R 126.16','Average sale']],rows:sites.map((site,index)=>[site,money(8940-index*1880),`+${12-index*3}.4%`] as [string,string,string])}};const data=details[module];
 return <div className="module-page"><div className="module-intro"><div><p>{client}</p><h2>{module}</h2><span>{data.subtitle}</span></div><button onClick={onBack}><ShoppingCart size={18}/> Open register</button></div>{module==='Inventory'&&<div className="inventory-scope"><Boxes size={18}/><div><strong>Client inventory catalogue</strong><span>Products, pricing and purchasing are managed once for all sites.</span></div><button><ArrowRightLeft size={16}/> Transfer stock</button></div>}<div className="stat-grid">{data.stats.map(([v,l])=><div className="stat-card" key={l}><span>{l}</span><strong>{v}</strong><small>Live across {sites.length} sites</small></div>)}</div><section className="data-card"><div><h3>{module==='Inventory'?'Stock by site':'Needs your attention'}</h3><button>View all <ChevronRight size={16}/></button></div>{data.rows.map(([n,v,s])=><article key={n}><span className="row-icon">{module==='Customers'?<Users/>:module==='Purchase orders'?<Truck/>:module==='Reports'?<BarChart3/>:<Boxes/>}</span><strong>{n}</strong><span>{v}</span><b>{s}</b></article>)}</section></div>
}
